package com.share_will.mobile.model.entity;

import java.io.Serializable;
import java.util.Date;

public class DepositRefundEntity implements Cloneable, Serializable {
    public static final String Table = "tb_deposit_refund";
    public static final String Alias = "as_tb_deposit_refund";
    private static final long serialVersionUID = 1L;
    public static final String DBStrId = "as_tb_deposit_refund.id";
    public static final String DBStrUserId = "as_tb_deposit_refund.user_id";
    public static final String DBStrMoney = "as_tb_deposit_refund.money";
    public static final String DBStrBankUserName = "as_tb_deposit_refund.bank_user_name";
    public static final String DBStrBankCard = "as_tb_deposit_refund.bank_card";
    public static final String DBStrBankName = "as_tb_deposit_refund.bank_name";
    public static final String DBStrDescription = "as_tb_deposit_refund.description";
    public static final String DBStrCauseStatus = "as_tb_deposit_refund.cause_status";
    public static final String DBStrAuditor = "as_tb_deposit_refund.auditor";
    public static final String DBStrResolve = "as_tb_deposit_refund.resolve";
    public static final String DBStrActive = "as_tb_deposit_refund.active";
    public static final String DBStrCreateTime = "as_tb_deposit_refund.create_time";
    public static final String DBStrCreator = "as_tb_deposit_refund.creator";
    public static final String DBStrModifyTime = "as_tb_deposit_refund.modify_time";
    public static final String DBStrModifier = "as_tb_deposit_refund.modifier";
    /**
     * This field was generated by THB Generator.
     * This field corresponds to the database column tb_deposit_refund.id
     * Remark - ID
     * DBType - INTEGER
     *
     * @mbggenerated Tue Aug 07 12:04:06 CST 2018
     */
    private Integer id;
    /**
     * This field was generated by THB Generator.
     * This field corresponds to the database column tb_deposit_refund.user_id
     * Remark - 用户手机号
     * DBType - VARCHAR
     *
     * @mbggenerated Tue Aug 07 12:04:06 CST 2018
     */
    private String userId;
    /**
     * This field was generated by THB Generator.
     * This field corresponds to the database column tb_deposit_refund.money
     * Remark - 退款金额
     * DBType - VARCHAR
     *
     * @mbggenerated Tue Aug 07 12:04:06 CST 2018
     */
    private String money;
    /**
     * This field was generated by THB Generator.
     * This field corresponds to the database column tb_deposit_refund.bank_user_name
     * Remark - 银行卡人姓名
     * DBType - VARCHAR
     *
     * @mbggenerated Tue Aug 07 12:04:06 CST 2018
     */
    private String bankUserName;
    /**
     * This field was generated by THB Generator.
     * This field corresponds to the database column tb_deposit_refund.bank_card
     * Remark - 银行卡号
     * DBType - VARCHAR
     *
     * @mbggenerated Tue Aug 07 12:04:06 CST 2018
     */
    private String bankCard;
    /**
     * This field was generated by THB Generator.
     * This field corresponds to the database column tb_deposit_refund.bank_name
     * Remark - 银行名称
     * DBType - VARCHAR
     *
     * @mbggenerated Tue Aug 07 12:04:06 CST 2018
     */
    private String bankName;
    /**
     * This field was generated by THB Generator.
     * This field corresponds to the database column tb_deposit_refund.description
     * Remark - 描述
     * DBType - VARCHAR
     *
     * @mbggenerated Tue Aug 07 12:04:06 CST 2018
     */
    private String description;
    /**
     * This field was generated by THB Generator.
     * This field corresponds to the database column tb_deposit_refund.cause_status
     * Remark - 状态0正在退款中1退款成功2拒绝退款3取消退款
     * DBType - SMALLINT
     *
     * @mbggenerated Tue Aug 07 12:04:06 CST 2018
     */
    private Integer causeStatus;
    /**
     * This field was generated by THB Generator.
     * This field corresponds to the database column tb_deposit_refund.auditor
     * Remark - 审核人
     * DBType - VARCHAR
     *
     * @mbggenerated Tue Aug 07 12:04:06 CST 2018
     */
    private String auditor;
    /**
     * This field was generated by THB Generator.
     * This field corresponds to the database column tb_deposit_refund.resolve
     * Remark - 审批结果
     * DBType - VARCHAR
     *
     * @mbggenerated Tue Aug 07 12:04:06 CST 2018
     */
    private String resolve;
    /**
     * This field was generated by THB Generator.
     * This field corresponds to the database column tb_deposit_refund.active
     * Remark - 是否有效(1有效0无效)
     * DBType - BIT
     *
     * @mbggenerated Tue Aug 07 12:04:06 CST 2018
     */
    private Boolean active;
    /**
     * This field was generated by THB Generator.
     * This field corresponds to the database column tb_deposit_refund.create_time
     * Remark - 创建时间
     * DBType - TIMESTAMP
     *
     * @mbggenerated Tue Aug 07 12:04:06 CST 2018
     */
    private long createTime;
    /**
     * This field was generated by THB Generator.
     * This field corresponds to the database column tb_deposit_refund.creator
     * Remark - 创建人
     * DBType - VARCHAR
     *
     * @mbggenerated Tue Aug 07 12:04:06 CST 2018
     */
    private String creator;
    /**
     * This field was generated by THB Generator.
     * This field corresponds to the database column tb_deposit_refund.modify_time
     * Remark - 修改时间
     * DBType - TIMESTAMP
     *
     * @mbggenerated Tue Aug 07 12:04:06 CST 2018
     */
    private long modifyTime;
    /**
     * This field was generated by THB Generator.
     * This field corresponds to the database column tb_deposit_refund.modifier
     * Remark - 修改人
     * DBType - VARCHAR
     *
     * @mbggenerated Tue Aug 07 12:04:06 CST 2018
     */
    private String modifier;

    public String userName;
    public String customerName;
    public String stationName;

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getCustomerName() {
        return customerName;
    }

    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    public String getStationName() {
        return stationName;
    }

    public void setStationName(String stationName) {
        this.stationName = stationName;
    }

    public DepositRefundEntity() {
        super();
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    public String getMoney() {
        return money;
    }

    public void setMoney(String money) {
        this.money = money == null ? null : money.trim();
    }

    public String getBankUserName() {
        return bankUserName;
    }

    public void setBankUserName(String bankUserName) {
        this.bankUserName = bankUserName == null ? null : bankUserName.trim();
    }

    public String getBankCard() {
        return bankCard;
    }

    public void setBankCard(String bankCard) {
        this.bankCard = bankCard == null ? null : bankCard.trim();
    }

    public String getBankName() {
        return bankName;
    }

    public void setBankName(String bankName) {
        this.bankName = bankName == null ? null : bankName.trim();
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    public Integer getCauseStatus() {
        return causeStatus;
    }

    public void setCauseStatus(Integer causeStatus) {
        this.causeStatus = causeStatus;
    }

    public String getAuditor() {
        return auditor;
    }

    public void setAuditor(String auditor) {
        this.auditor = auditor == null ? null : auditor.trim();
    }

    public String getResolve() {
        return resolve;
    }

    public void setResolve(String resolve) {
        this.resolve = resolve == null ? null : resolve.trim();
    }

    public Boolean getActive() {
        return active;
    }

    public void setActive(Boolean active) {
        this.active = active;
    }

    public Date getCreateTime() {
        return new Date(createTime);
    }

    public void setCreateTime(long createTime) {
        this.createTime = createTime;
    }

    public String getCreator() {
        return creator;
    }

    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    public Date getModifyTime() {
        return new Date(modifyTime);
    }

    public void setModifyTime(long modifyTime) {
        this.modifyTime = modifyTime;
    }

    public String getModifier() {
        return modifier;
    }

    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    public DepositRefundEntity clone() {
        DepositRefundEntity o = null;
        try{
            o = (DepositRefundEntity)super.clone();
        }catch(CloneNotSupportedException ex){
            ex.printStackTrace();
        }
        return o;
    }
}